server:
  name: "distributor-svc"
  port: ":8004"
  log:
    level: "debug"
    format: "text"

database:
  sql:
    url: "postgresql://postgres:postgres@localhost:7777/postgres?sslmode=disable"

jwt:
  user:
    access_token:
      secret_key: "supersecretkey"
      token_lifetime: 900
  service:
    secret_key: "servicesuperkey"
  employee-invites:
    secret_key: "invitesuperkey"

kafka:
  brokers:
    - "re-news-kafka:XXXX"

swagger:
  enabled: true
  url: "/swagger"
  port: "XXXX"

properties:
  residence:
    api_key: "apikey" #form https://rapidapi.com/wirefreethought/api/geodb-cities