/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCompany type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCompany{}

// CreateCompany struct for CreateCompany
type CreateCompany struct {
	Data CreateCompanyData `json:"data"`
}

type _CreateCompany CreateCompany

// NewCreateCompany instantiates a new CreateCompany object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCompany(data CreateCompanyData) *CreateCompany {
	this := CreateCompany{}
	this.Data = data
	return &this
}

// NewCreateCompanyWithDefaults instantiates a new CreateCompany object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCompanyWithDefaults() *CreateCompany {
	this := CreateCompany{}
	return &this
}

// GetData returns the Data field value
func (o *CreateCompany) GetData() CreateCompanyData {
	if o == nil {
		var ret CreateCompanyData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateCompany) GetDataOk() (*CreateCompanyData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateCompany) SetData(v CreateCompanyData) {
	o.Data = v
}

func (o CreateCompany) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCompany) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateCompany) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCompany := _CreateCompany{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCompany)

	if err != nil {
		return err
	}

	*o = CreateCompany(varCreateCompany)

	return err
}

type NullableCreateCompany struct {
	value *CreateCompany
	isSet bool
}

func (v NullableCreateCompany) Get() *CreateCompany {
	return v.value
}

func (v *NullableCreateCompany) Set(val *CreateCompany) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCompany) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCompany) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCompany(val *CreateCompany) *NullableCreateCompany {
	return &NullableCreateCompany{value: val, isSet: true}
}

func (v NullableCreateCompany) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCompany) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


