/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateMyEmployeeDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMyEmployeeDataAttributes{}

// UpdateMyEmployeeDataAttributes struct for UpdateMyEmployeeDataAttributes
type UpdateMyEmployeeDataAttributes struct {
	// The job title of the employee.
	Position *string `json:"position,omitempty"`
	// A label or tag associated with the employee.
	Label *string `json:"label,omitempty"`
}

// NewUpdateMyEmployeeDataAttributes instantiates a new UpdateMyEmployeeDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMyEmployeeDataAttributes() *UpdateMyEmployeeDataAttributes {
	this := UpdateMyEmployeeDataAttributes{}
	return &this
}

// NewUpdateMyEmployeeDataAttributesWithDefaults instantiates a new UpdateMyEmployeeDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMyEmployeeDataAttributesWithDefaults() *UpdateMyEmployeeDataAttributes {
	this := UpdateMyEmployeeDataAttributes{}
	return &this
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *UpdateMyEmployeeDataAttributes) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMyEmployeeDataAttributes) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *UpdateMyEmployeeDataAttributes) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *UpdateMyEmployeeDataAttributes) SetPosition(v string) {
	o.Position = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *UpdateMyEmployeeDataAttributes) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMyEmployeeDataAttributes) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *UpdateMyEmployeeDataAttributes) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *UpdateMyEmployeeDataAttributes) SetLabel(v string) {
	o.Label = &v
}

func (o UpdateMyEmployeeDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMyEmployeeDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableUpdateMyEmployeeDataAttributes struct {
	value *UpdateMyEmployeeDataAttributes
	isSet bool
}

func (v NullableUpdateMyEmployeeDataAttributes) Get() *UpdateMyEmployeeDataAttributes {
	return v.value
}

func (v *NullableUpdateMyEmployeeDataAttributes) Set(val *UpdateMyEmployeeDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMyEmployeeDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMyEmployeeDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMyEmployeeDataAttributes(val *UpdateMyEmployeeDataAttributes) *NullableUpdateMyEmployeeDataAttributes {
	return &NullableUpdateMyEmployeeDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateMyEmployeeDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMyEmployeeDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


