/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateCompanyDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCompanyDataAttributes{}

// UpdateCompanyDataAttributes struct for UpdateCompanyDataAttributes
type UpdateCompanyDataAttributes struct {
	// URL to the company's icon image.
	Icon *string `json:"icon,omitempty"`
	// The name of the company.
	Name *string `json:"name,omitempty"`
}

// NewUpdateCompanyDataAttributes instantiates a new UpdateCompanyDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCompanyDataAttributes() *UpdateCompanyDataAttributes {
	this := UpdateCompanyDataAttributes{}
	return &this
}

// NewUpdateCompanyDataAttributesWithDefaults instantiates a new UpdateCompanyDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCompanyDataAttributesWithDefaults() *UpdateCompanyDataAttributes {
	this := UpdateCompanyDataAttributes{}
	return &this
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *UpdateCompanyDataAttributes) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCompanyDataAttributes) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *UpdateCompanyDataAttributes) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *UpdateCompanyDataAttributes) SetIcon(v string) {
	o.Icon = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateCompanyDataAttributes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCompanyDataAttributes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateCompanyDataAttributes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateCompanyDataAttributes) SetName(v string) {
	o.Name = &v
}

func (o UpdateCompanyDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCompanyDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableUpdateCompanyDataAttributes struct {
	value *UpdateCompanyDataAttributes
	isSet bool
}

func (v NullableUpdateCompanyDataAttributes) Get() *UpdateCompanyDataAttributes {
	return v.value
}

func (v *NullableUpdateCompanyDataAttributes) Set(val *UpdateCompanyDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCompanyDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCompanyDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCompanyDataAttributes(val *UpdateCompanyDataAttributes) *NullableUpdateCompanyDataAttributes {
	return &NullableUpdateCompanyDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateCompanyDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCompanyDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


