/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompaniesCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompaniesCollection{}

// CompaniesCollection struct for CompaniesCollection
type CompaniesCollection struct {
	Data []CompanyData `json:"data"`
	Links PaginationData `json:"links"`
}

type _CompaniesCollection CompaniesCollection

// NewCompaniesCollection instantiates a new CompaniesCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompaniesCollection(data []CompanyData, links PaginationData) *CompaniesCollection {
	this := CompaniesCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewCompaniesCollectionWithDefaults instantiates a new CompaniesCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompaniesCollectionWithDefaults() *CompaniesCollection {
	this := CompaniesCollection{}
	return &this
}

// GetData returns the Data field value
func (o *CompaniesCollection) GetData() []CompanyData {
	if o == nil {
		var ret []CompanyData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CompaniesCollection) GetDataOk() ([]CompanyData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CompaniesCollection) SetData(v []CompanyData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *CompaniesCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *CompaniesCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *CompaniesCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o CompaniesCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompaniesCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *CompaniesCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompaniesCollection := _CompaniesCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompaniesCollection)

	if err != nil {
		return err
	}

	*o = CompaniesCollection(varCompaniesCollection)

	return err
}

type NullableCompaniesCollection struct {
	value *CompaniesCollection
	isSet bool
}

func (v NullableCompaniesCollection) Get() *CompaniesCollection {
	return v.value
}

func (v *NullableCompaniesCollection) Set(val *CompaniesCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableCompaniesCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableCompaniesCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompaniesCollection(val *CompaniesCollection) *NullableCompaniesCollection {
	return &NullableCompaniesCollection{value: val, isSet: true}
}

func (v NullableCompaniesCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompaniesCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


