/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCompanyDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCompanyDataAttributes{}

// CreateCompanyDataAttributes struct for CreateCompanyDataAttributes
type CreateCompanyDataAttributes struct {
	// URL to the company's icon image.
	Icon string `json:"icon"`
	// The name of the company.
	Name string `json:"name"`
}

type _CreateCompanyDataAttributes CreateCompanyDataAttributes

// NewCreateCompanyDataAttributes instantiates a new CreateCompanyDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCompanyDataAttributes(icon string, name string) *CreateCompanyDataAttributes {
	this := CreateCompanyDataAttributes{}
	this.Icon = icon
	this.Name = name
	return &this
}

// NewCreateCompanyDataAttributesWithDefaults instantiates a new CreateCompanyDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCompanyDataAttributesWithDefaults() *CreateCompanyDataAttributes {
	this := CreateCompanyDataAttributes{}
	return &this
}

// GetIcon returns the Icon field value
func (o *CreateCompanyDataAttributes) GetIcon() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Icon
}

// GetIconOk returns a tuple with the Icon field value
// and a boolean to check if the value has been set.
func (o *CreateCompanyDataAttributes) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icon, true
}

// SetIcon sets field value
func (o *CreateCompanyDataAttributes) SetIcon(v string) {
	o.Icon = v
}

// GetName returns the Name field value
func (o *CreateCompanyDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateCompanyDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateCompanyDataAttributes) SetName(v string) {
	o.Name = v
}

func (o CreateCompanyDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCompanyDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["icon"] = o.Icon
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateCompanyDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"icon",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCompanyDataAttributes := _CreateCompanyDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCompanyDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateCompanyDataAttributes(varCreateCompanyDataAttributes)

	return err
}

type NullableCreateCompanyDataAttributes struct {
	value *CreateCompanyDataAttributes
	isSet bool
}

func (v NullableCreateCompanyDataAttributes) Get() *CreateCompanyDataAttributes {
	return v.value
}

func (v *NullableCreateCompanyDataAttributes) Set(val *CreateCompanyDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCompanyDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCompanyDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCompanyDataAttributes(val *CreateCompanyDataAttributes) *NullableCreateCompanyDataAttributes {
	return &NullableCreateCompanyDataAttributes{value: val, isSet: true}
}

func (v NullableCreateCompanyDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCompanyDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


