/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeeInviteData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeInviteData{}

// EmployeeInviteData struct for EmployeeInviteData
type EmployeeInviteData struct {
	// employee invite id
	Id string `json:"id"`
	Type string `json:"type"`
	Attributes EmployeeInviteAttributes `json:"attributes"`
}

type _EmployeeInviteData EmployeeInviteData

// NewEmployeeInviteData instantiates a new EmployeeInviteData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeInviteData(id string, type_ string, attributes EmployeeInviteAttributes) *EmployeeInviteData {
	this := EmployeeInviteData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewEmployeeInviteDataWithDefaults instantiates a new EmployeeInviteData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeInviteDataWithDefaults() *EmployeeInviteData {
	this := EmployeeInviteData{}
	return &this
}

// GetId returns the Id field value
func (o *EmployeeInviteData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EmployeeInviteData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EmployeeInviteData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *EmployeeInviteData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EmployeeInviteData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EmployeeInviteData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *EmployeeInviteData) GetAttributes() EmployeeInviteAttributes {
	if o == nil {
		var ret EmployeeInviteAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *EmployeeInviteData) GetAttributesOk() (*EmployeeInviteAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *EmployeeInviteData) SetAttributes(v EmployeeInviteAttributes) {
	o.Attributes = v
}

func (o EmployeeInviteData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeInviteData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *EmployeeInviteData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeInviteData := _EmployeeInviteData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeInviteData)

	if err != nil {
		return err
	}

	*o = EmployeeInviteData(varEmployeeInviteData)

	return err
}

type NullableEmployeeInviteData struct {
	value *EmployeeInviteData
	isSet bool
}

func (v NullableEmployeeInviteData) Get() *EmployeeInviteData {
	return v.value
}

func (v *NullableEmployeeInviteData) Set(val *EmployeeInviteData) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeInviteData) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeInviteData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeInviteData(val *EmployeeInviteData) *NullableEmployeeInviteData {
	return &NullableEmployeeInviteData{value: val, isSet: true}
}

func (v NullableEmployeeInviteData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeInviteData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


