/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCompanyBlockData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCompanyBlockData{}

// CreateCompanyBlockData struct for CreateCompanyBlockData
type CreateCompanyBlockData struct {
	Type string `json:"type"`
	Attributes CreateCompanyBlockDataAttributes `json:"attributes"`
}

type _CreateCompanyBlockData CreateCompanyBlockData

// NewCreateCompanyBlockData instantiates a new CreateCompanyBlockData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCompanyBlockData(type_ string, attributes CreateCompanyBlockDataAttributes) *CreateCompanyBlockData {
	this := CreateCompanyBlockData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateCompanyBlockDataWithDefaults instantiates a new CreateCompanyBlockData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCompanyBlockDataWithDefaults() *CreateCompanyBlockData {
	this := CreateCompanyBlockData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateCompanyBlockData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateCompanyBlockData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateCompanyBlockData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateCompanyBlockData) GetAttributes() CreateCompanyBlockDataAttributes {
	if o == nil {
		var ret CreateCompanyBlockDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateCompanyBlockData) GetAttributesOk() (*CreateCompanyBlockDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateCompanyBlockData) SetAttributes(v CreateCompanyBlockDataAttributes) {
	o.Attributes = v
}

func (o CreateCompanyBlockData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCompanyBlockData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateCompanyBlockData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCompanyBlockData := _CreateCompanyBlockData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCompanyBlockData)

	if err != nil {
		return err
	}

	*o = CreateCompanyBlockData(varCreateCompanyBlockData)

	return err
}

type NullableCreateCompanyBlockData struct {
	value *CreateCompanyBlockData
	isSet bool
}

func (v NullableCreateCompanyBlockData) Get() *CreateCompanyBlockData {
	return v.value
}

func (v *NullableCreateCompanyBlockData) Set(val *CreateCompanyBlockData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCompanyBlockData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCompanyBlockData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCompanyBlockData(val *CreateCompanyBlockData) *NullableCreateCompanyBlockData {
	return &NullableCreateCompanyBlockData{value: val, isSet: true}
}

func (v NullableCreateCompanyBlockData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCompanyBlockData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


