/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"time"
	"bytes"
	"fmt"
)

// checks if the EmployeeAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeAttributes{}

// EmployeeAttributes struct for EmployeeAttributes
type EmployeeAttributes struct {
	// The unique identifier for the company associated with the employee.
	CompanyId uuid.UUID `json:"company_id"`
	// The role of the employee within the company's organization (e.g., manager, staff).
	Role string `json:"role"`
	// The job position or title of the employee.
	Position *string `json:"position,omitempty"`
	// A human-readable label or name for the employee.
	Label *string `json:"label,omitempty"`
	// The timestamp when the employee record was created.
	CreatedAt time.Time `json:"created_at"`
	// The timestamp when the employee record was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

type _EmployeeAttributes EmployeeAttributes

// NewEmployeeAttributes instantiates a new EmployeeAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeAttributes(companyId uuid.UUID, role string, createdAt time.Time, updatedAt time.Time) *EmployeeAttributes {
	this := EmployeeAttributes{}
	this.CompanyId = companyId
	this.Role = role
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewEmployeeAttributesWithDefaults instantiates a new EmployeeAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeAttributesWithDefaults() *EmployeeAttributes {
	this := EmployeeAttributes{}
	return &this
}

// GetCompanyId returns the CompanyId field value
func (o *EmployeeAttributes) GetCompanyId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *EmployeeAttributes) GetCompanyIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *EmployeeAttributes) SetCompanyId(v uuid.UUID) {
	o.CompanyId = v
}

// GetRole returns the Role field value
func (o *EmployeeAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *EmployeeAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *EmployeeAttributes) SetRole(v string) {
	o.Role = v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *EmployeeAttributes) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeAttributes) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *EmployeeAttributes) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *EmployeeAttributes) SetPosition(v string) {
	o.Position = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *EmployeeAttributes) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeAttributes) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *EmployeeAttributes) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *EmployeeAttributes) SetLabel(v string) {
	o.Label = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *EmployeeAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EmployeeAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EmployeeAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *EmployeeAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *EmployeeAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *EmployeeAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o EmployeeAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["company_id"] = o.CompanyId
	toSerialize["role"] = o.Role
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *EmployeeAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"company_id",
		"role",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeAttributes := _EmployeeAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeAttributes)

	if err != nil {
		return err
	}

	*o = EmployeeAttributes(varEmployeeAttributes)

	return err
}

type NullableEmployeeAttributes struct {
	value *EmployeeAttributes
	isSet bool
}

func (v NullableEmployeeAttributes) Get() *EmployeeAttributes {
	return v.value
}

func (v *NullableEmployeeAttributes) Set(val *EmployeeAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeAttributes(val *EmployeeAttributes) *NullableEmployeeAttributes {
	return &NullableEmployeeAttributes{value: val, isSet: true}
}

func (v NullableEmployeeAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


