/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateMyEmployeeData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMyEmployeeData{}

// UpdateMyEmployeeData struct for UpdateMyEmployeeData
type UpdateMyEmployeeData struct {
	// user id + company id (UUID:UUID)
	Id string `json:"id" validate:"regexp=^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"`
	Type string `json:"type"`
	Attributes UpdateMyEmployeeDataAttributes `json:"attributes"`
}

type _UpdateMyEmployeeData UpdateMyEmployeeData

// NewUpdateMyEmployeeData instantiates a new UpdateMyEmployeeData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMyEmployeeData(id string, type_ string, attributes UpdateMyEmployeeDataAttributes) *UpdateMyEmployeeData {
	this := UpdateMyEmployeeData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateMyEmployeeDataWithDefaults instantiates a new UpdateMyEmployeeData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMyEmployeeDataWithDefaults() *UpdateMyEmployeeData {
	this := UpdateMyEmployeeData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateMyEmployeeData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateMyEmployeeData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateMyEmployeeData) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateMyEmployeeData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateMyEmployeeData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateMyEmployeeData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateMyEmployeeData) GetAttributes() UpdateMyEmployeeDataAttributes {
	if o == nil {
		var ret UpdateMyEmployeeDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateMyEmployeeData) GetAttributesOk() (*UpdateMyEmployeeDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateMyEmployeeData) SetAttributes(v UpdateMyEmployeeDataAttributes) {
	o.Attributes = v
}

func (o UpdateMyEmployeeData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMyEmployeeData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateMyEmployeeData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMyEmployeeData := _UpdateMyEmployeeData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateMyEmployeeData)

	if err != nil {
		return err
	}

	*o = UpdateMyEmployeeData(varUpdateMyEmployeeData)

	return err
}

type NullableUpdateMyEmployeeData struct {
	value *UpdateMyEmployeeData
	isSet bool
}

func (v NullableUpdateMyEmployeeData) Get() *UpdateMyEmployeeData {
	return v.value
}

func (v *NullableUpdateMyEmployeeData) Set(val *UpdateMyEmployeeData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMyEmployeeData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMyEmployeeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMyEmployeeData(val *UpdateMyEmployeeData) *NullableUpdateMyEmployeeData {
	return &NullableUpdateMyEmployeeData{value: val, isSet: true}
}

func (v NullableUpdateMyEmployeeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMyEmployeeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


