/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompanyBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyBlock{}

// CompanyBlock struct for CompanyBlock
type CompanyBlock struct {
	Data CompanyBlockData `json:"data"`
}

type _CompanyBlock CompanyBlock

// NewCompanyBlock instantiates a new CompanyBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyBlock(data CompanyBlockData) *CompanyBlock {
	this := CompanyBlock{}
	this.Data = data
	return &this
}

// NewCompanyBlockWithDefaults instantiates a new CompanyBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyBlockWithDefaults() *CompanyBlock {
	this := CompanyBlock{}
	return &this
}

// GetData returns the Data field value
func (o *CompanyBlock) GetData() CompanyBlockData {
	if o == nil {
		var ret CompanyBlockData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CompanyBlock) GetDataOk() (*CompanyBlockData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CompanyBlock) SetData(v CompanyBlockData) {
	o.Data = v
}

func (o CompanyBlock) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CompanyBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompanyBlock := _CompanyBlock{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompanyBlock)

	if err != nil {
		return err
	}

	*o = CompanyBlock(varCompanyBlock)

	return err
}

type NullableCompanyBlock struct {
	value *CompanyBlock
	isSet bool
}

func (v NullableCompanyBlock) Get() *CompanyBlock {
	return v.value
}

func (v *NullableCompanyBlock) Set(val *CompanyBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyBlock(val *CompanyBlock) *NullableCompanyBlock {
	return &NullableCompanyBlock{value: val, isSet: true}
}

func (v NullableCompanyBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


