/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeesInvitesCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeesInvitesCollection{}

// EmployeesInvitesCollection struct for EmployeesInvitesCollection
type EmployeesInvitesCollection struct {
	Data []EmployeeInviteData `json:"data"`
	Links PaginationData `json:"links"`
}

type _EmployeesInvitesCollection EmployeesInvitesCollection

// NewEmployeesInvitesCollection instantiates a new EmployeesInvitesCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeesInvitesCollection(data []EmployeeInviteData, links PaginationData) *EmployeesInvitesCollection {
	this := EmployeesInvitesCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewEmployeesInvitesCollectionWithDefaults instantiates a new EmployeesInvitesCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeesInvitesCollectionWithDefaults() *EmployeesInvitesCollection {
	this := EmployeesInvitesCollection{}
	return &this
}

// GetData returns the Data field value
func (o *EmployeesInvitesCollection) GetData() []EmployeeInviteData {
	if o == nil {
		var ret []EmployeeInviteData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *EmployeesInvitesCollection) GetDataOk() ([]EmployeeInviteData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *EmployeesInvitesCollection) SetData(v []EmployeeInviteData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *EmployeesInvitesCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *EmployeesInvitesCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *EmployeesInvitesCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o EmployeesInvitesCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeesInvitesCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *EmployeesInvitesCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeesInvitesCollection := _EmployeesInvitesCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeesInvitesCollection)

	if err != nil {
		return err
	}

	*o = EmployeesInvitesCollection(varEmployeesInvitesCollection)

	return err
}

type NullableEmployeesInvitesCollection struct {
	value *EmployeesInvitesCollection
	isSet bool
}

func (v NullableEmployeesInvitesCollection) Get() *EmployeesInvitesCollection {
	return v.value
}

func (v *NullableEmployeesInvitesCollection) Set(val *EmployeesInvitesCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeesInvitesCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeesInvitesCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeesInvitesCollection(val *EmployeesInvitesCollection) *NullableEmployeesInvitesCollection {
	return &NullableEmployeesInvitesCollection{value: val, isSet: true}
}

func (v NullableEmployeesInvitesCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeesInvitesCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


