/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AnswerInviteDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnswerInviteDataAttributes{}

// AnswerInviteDataAttributes struct for AnswerInviteDataAttributes
type AnswerInviteDataAttributes struct {
	// The answer to the invite, either 'accept' or 'decline'
	Answer string `json:"answer"`
}

type _AnswerInviteDataAttributes AnswerInviteDataAttributes

// NewAnswerInviteDataAttributes instantiates a new AnswerInviteDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnswerInviteDataAttributes(answer string) *AnswerInviteDataAttributes {
	this := AnswerInviteDataAttributes{}
	this.Answer = answer
	return &this
}

// NewAnswerInviteDataAttributesWithDefaults instantiates a new AnswerInviteDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnswerInviteDataAttributesWithDefaults() *AnswerInviteDataAttributes {
	this := AnswerInviteDataAttributes{}
	return &this
}

// GetAnswer returns the Answer field value
func (o *AnswerInviteDataAttributes) GetAnswer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Answer
}

// GetAnswerOk returns a tuple with the Answer field value
// and a boolean to check if the value has been set.
func (o *AnswerInviteDataAttributes) GetAnswerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Answer, true
}

// SetAnswer sets field value
func (o *AnswerInviteDataAttributes) SetAnswer(v string) {
	o.Answer = v
}

func (o AnswerInviteDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnswerInviteDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["answer"] = o.Answer
	return toSerialize, nil
}

func (o *AnswerInviteDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"answer",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnswerInviteDataAttributes := _AnswerInviteDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnswerInviteDataAttributes)

	if err != nil {
		return err
	}

	*o = AnswerInviteDataAttributes(varAnswerInviteDataAttributes)

	return err
}

type NullableAnswerInviteDataAttributes struct {
	value *AnswerInviteDataAttributes
	isSet bool
}

func (v NullableAnswerInviteDataAttributes) Get() *AnswerInviteDataAttributes {
	return v.value
}

func (v *NullableAnswerInviteDataAttributes) Set(val *AnswerInviteDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAnswerInviteDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAnswerInviteDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnswerInviteDataAttributes(val *AnswerInviteDataAttributes) *NullableAnswerInviteDataAttributes {
	return &NullableAnswerInviteDataAttributes{value: val, isSet: true}
}

func (v NullableAnswerInviteDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnswerInviteDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


