/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the EmployeeInviteAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeInviteAttributes{}

// EmployeeInviteAttributes struct for EmployeeInviteAttributes
type EmployeeInviteAttributes struct {
	// The unique identifier for the distributor associated with the employee invite.
	DistributorId string `json:"distributor_id"`
	// The unique identifier for the user being invited as an employee.
	UserId string `json:"user_id"`
	// The unique identifier for the user who sent the invitation.
	InvitedBy string `json:"invited_by"`
	// The role of the invited employee within the distributor's organization (e.g., manager, staff).
	Role string `json:"role"`
	// The current status of the employee invitation.
	Status string `json:"status"`
	// The timestamp when the invitation was responded to (accepted or declined).
	AnsweredAt *time.Time `json:"answered_at,omitempty"`
	// The timestamp when the employee invite was created.
	CreatedAt time.Time `json:"created_at"`
}

type _EmployeeInviteAttributes EmployeeInviteAttributes

// NewEmployeeInviteAttributes instantiates a new EmployeeInviteAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeInviteAttributes(distributorId string, userId string, invitedBy string, role string, status string, createdAt time.Time) *EmployeeInviteAttributes {
	this := EmployeeInviteAttributes{}
	this.DistributorId = distributorId
	this.UserId = userId
	this.InvitedBy = invitedBy
	this.Role = role
	this.Status = status
	this.CreatedAt = createdAt
	return &this
}

// NewEmployeeInviteAttributesWithDefaults instantiates a new EmployeeInviteAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeInviteAttributesWithDefaults() *EmployeeInviteAttributes {
	this := EmployeeInviteAttributes{}
	return &this
}

// GetDistributorId returns the DistributorId field value
func (o *EmployeeInviteAttributes) GetDistributorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DistributorId
}

// GetDistributorIdOk returns a tuple with the DistributorId field value
// and a boolean to check if the value has been set.
func (o *EmployeeInviteAttributes) GetDistributorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistributorId, true
}

// SetDistributorId sets field value
func (o *EmployeeInviteAttributes) SetDistributorId(v string) {
	o.DistributorId = v
}

// GetUserId returns the UserId field value
func (o *EmployeeInviteAttributes) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *EmployeeInviteAttributes) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *EmployeeInviteAttributes) SetUserId(v string) {
	o.UserId = v
}

// GetInvitedBy returns the InvitedBy field value
func (o *EmployeeInviteAttributes) GetInvitedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvitedBy
}

// GetInvitedByOk returns a tuple with the InvitedBy field value
// and a boolean to check if the value has been set.
func (o *EmployeeInviteAttributes) GetInvitedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvitedBy, true
}

// SetInvitedBy sets field value
func (o *EmployeeInviteAttributes) SetInvitedBy(v string) {
	o.InvitedBy = v
}

// GetRole returns the Role field value
func (o *EmployeeInviteAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *EmployeeInviteAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *EmployeeInviteAttributes) SetRole(v string) {
	o.Role = v
}

// GetStatus returns the Status field value
func (o *EmployeeInviteAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *EmployeeInviteAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *EmployeeInviteAttributes) SetStatus(v string) {
	o.Status = v
}

// GetAnsweredAt returns the AnsweredAt field value if set, zero value otherwise.
func (o *EmployeeInviteAttributes) GetAnsweredAt() time.Time {
	if o == nil || IsNil(o.AnsweredAt) {
		var ret time.Time
		return ret
	}
	return *o.AnsweredAt
}

// GetAnsweredAtOk returns a tuple with the AnsweredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmployeeInviteAttributes) GetAnsweredAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AnsweredAt) {
		return nil, false
	}
	return o.AnsweredAt, true
}

// HasAnsweredAt returns a boolean if a field has been set.
func (o *EmployeeInviteAttributes) HasAnsweredAt() bool {
	if o != nil && !IsNil(o.AnsweredAt) {
		return true
	}

	return false
}

// SetAnsweredAt gets a reference to the given time.Time and assigns it to the AnsweredAt field.
func (o *EmployeeInviteAttributes) SetAnsweredAt(v time.Time) {
	o.AnsweredAt = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *EmployeeInviteAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EmployeeInviteAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EmployeeInviteAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o EmployeeInviteAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeInviteAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["distributor_id"] = o.DistributorId
	toSerialize["user_id"] = o.UserId
	toSerialize["invited_by"] = o.InvitedBy
	toSerialize["role"] = o.Role
	toSerialize["status"] = o.Status
	if !IsNil(o.AnsweredAt) {
		toSerialize["answered_at"] = o.AnsweredAt
	}
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *EmployeeInviteAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"distributor_id",
		"user_id",
		"invited_by",
		"role",
		"status",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeInviteAttributes := _EmployeeInviteAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeInviteAttributes)

	if err != nil {
		return err
	}

	*o = EmployeeInviteAttributes(varEmployeeInviteAttributes)

	return err
}

type NullableEmployeeInviteAttributes struct {
	value *EmployeeInviteAttributes
	isSet bool
}

func (v NullableEmployeeInviteAttributes) Get() *EmployeeInviteAttributes {
	return v.value
}

func (v *NullableEmployeeInviteAttributes) Set(val *EmployeeInviteAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeInviteAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeInviteAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeInviteAttributes(val *EmployeeInviteAttributes) *NullableEmployeeInviteAttributes {
	return &NullableEmployeeInviteAttributes{value: val, isSet: true}
}

func (v NullableEmployeeInviteAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeInviteAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


