/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"time"
	"bytes"
	"fmt"
)

// checks if the EmployeeAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeeAttributes{}

// EmployeeAttributes struct for EmployeeAttributes
type EmployeeAttributes struct {
	// The unique identifier for the distributor associated with the employee.
	DistributorId uuid.UUID `json:"distributor_id"`
	// The role of the employee within the distributor's organization (e.g., manager, staff).
	Role string `json:"role"`
	// The timestamp when the employee record was created.
	CreatedAt time.Time `json:"created_at"`
	// The timestamp when the employee record was last updated.
	UpdatedAt time.Time `json:"updated_at"`
}

type _EmployeeAttributes EmployeeAttributes

// NewEmployeeAttributes instantiates a new EmployeeAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeeAttributes(distributorId uuid.UUID, role string, createdAt time.Time, updatedAt time.Time) *EmployeeAttributes {
	this := EmployeeAttributes{}
	this.DistributorId = distributorId
	this.Role = role
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewEmployeeAttributesWithDefaults instantiates a new EmployeeAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeeAttributesWithDefaults() *EmployeeAttributes {
	this := EmployeeAttributes{}
	return &this
}

// GetDistributorId returns the DistributorId field value
func (o *EmployeeAttributes) GetDistributorId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.DistributorId
}

// GetDistributorIdOk returns a tuple with the DistributorId field value
// and a boolean to check if the value has been set.
func (o *EmployeeAttributes) GetDistributorIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistributorId, true
}

// SetDistributorId sets field value
func (o *EmployeeAttributes) SetDistributorId(v uuid.UUID) {
	o.DistributorId = v
}

// GetRole returns the Role field value
func (o *EmployeeAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *EmployeeAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *EmployeeAttributes) SetRole(v string) {
	o.Role = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *EmployeeAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EmployeeAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EmployeeAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *EmployeeAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *EmployeeAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *EmployeeAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o EmployeeAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeeAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["distributor_id"] = o.DistributorId
	toSerialize["role"] = o.Role
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *EmployeeAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"distributor_id",
		"role",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeeAttributes := _EmployeeAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeeAttributes)

	if err != nil {
		return err
	}

	*o = EmployeeAttributes(varEmployeeAttributes)

	return err
}

type NullableEmployeeAttributes struct {
	value *EmployeeAttributes
	isSet bool
}

func (v NullableEmployeeAttributes) Get() *EmployeeAttributes {
	return v.value
}

func (v *NullableEmployeeAttributes) Set(val *EmployeeAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeAttributes(val *EmployeeAttributes) *NullableEmployeeAttributes {
	return &NullableEmployeeAttributes{value: val, isSet: true}
}

func (v NullableEmployeeAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


