/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDistributorBlockData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDistributorBlockData{}

// CreateDistributorBlockData struct for CreateDistributorBlockData
type CreateDistributorBlockData struct {
	Type string `json:"type"`
	Attributes CreateDistributorBlockDataAttributes `json:"attributes"`
}

type _CreateDistributorBlockData CreateDistributorBlockData

// NewCreateDistributorBlockData instantiates a new CreateDistributorBlockData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDistributorBlockData(type_ string, attributes CreateDistributorBlockDataAttributes) *CreateDistributorBlockData {
	this := CreateDistributorBlockData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateDistributorBlockDataWithDefaults instantiates a new CreateDistributorBlockData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDistributorBlockDataWithDefaults() *CreateDistributorBlockData {
	this := CreateDistributorBlockData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateDistributorBlockData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateDistributorBlockData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateDistributorBlockData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateDistributorBlockData) GetAttributes() CreateDistributorBlockDataAttributes {
	if o == nil {
		var ret CreateDistributorBlockDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateDistributorBlockData) GetAttributesOk() (*CreateDistributorBlockDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateDistributorBlockData) SetAttributes(v CreateDistributorBlockDataAttributes) {
	o.Attributes = v
}

func (o CreateDistributorBlockData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDistributorBlockData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateDistributorBlockData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDistributorBlockData := _CreateDistributorBlockData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDistributorBlockData)

	if err != nil {
		return err
	}

	*o = CreateDistributorBlockData(varCreateDistributorBlockData)

	return err
}

type NullableCreateDistributorBlockData struct {
	value *CreateDistributorBlockData
	isSet bool
}

func (v NullableCreateDistributorBlockData) Get() *CreateDistributorBlockData {
	return v.value
}

func (v *NullableCreateDistributorBlockData) Set(val *CreateDistributorBlockData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDistributorBlockData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDistributorBlockData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDistributorBlockData(val *CreateDistributorBlockData) *NullableCreateDistributorBlockData {
	return &NullableCreateDistributorBlockData{value: val, isSet: true}
}

func (v NullableCreateDistributorBlockData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDistributorBlockData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


