/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCompanyStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCompanyStatus{}

// UpdateCompanyStatus struct for UpdateCompanyStatus
type UpdateCompanyStatus struct {
	Data UpdateCompanyStatusData `json:"data"`
}

type _UpdateCompanyStatus UpdateCompanyStatus

// NewUpdateCompanyStatus instantiates a new UpdateCompanyStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCompanyStatus(data UpdateCompanyStatusData) *UpdateCompanyStatus {
	this := UpdateCompanyStatus{}
	this.Data = data
	return &this
}

// NewUpdateCompanyStatusWithDefaults instantiates a new UpdateCompanyStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCompanyStatusWithDefaults() *UpdateCompanyStatus {
	this := UpdateCompanyStatus{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateCompanyStatus) GetData() UpdateCompanyStatusData {
	if o == nil {
		var ret UpdateCompanyStatusData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateCompanyStatus) GetDataOk() (*UpdateCompanyStatusData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateCompanyStatus) SetData(v UpdateCompanyStatusData) {
	o.Data = v
}

func (o UpdateCompanyStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCompanyStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateCompanyStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCompanyStatus := _UpdateCompanyStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCompanyStatus)

	if err != nil {
		return err
	}

	*o = UpdateCompanyStatus(varUpdateCompanyStatus)

	return err
}

type NullableUpdateCompanyStatus struct {
	value *UpdateCompanyStatus
	isSet bool
}

func (v NullableUpdateCompanyStatus) Get() *UpdateCompanyStatus {
	return v.value
}

func (v *NullableUpdateCompanyStatus) Set(val *UpdateCompanyStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCompanyStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCompanyStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCompanyStatus(val *UpdateCompanyStatus) *NullableUpdateCompanyStatus {
	return &NullableUpdateCompanyStatus{value: val, isSet: true}
}

func (v NullableUpdateCompanyStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCompanyStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


