/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReplyToInviteDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReplyToInviteDataAttributes{}

// ReplyToInviteDataAttributes struct for ReplyToInviteDataAttributes
type ReplyToInviteDataAttributes struct {
	// The reply to the invite, either 'accept' or 'decline'
	Reply string `json:"reply"`
}

type _ReplyToInviteDataAttributes ReplyToInviteDataAttributes

// NewReplyToInviteDataAttributes instantiates a new ReplyToInviteDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplyToInviteDataAttributes(reply string) *ReplyToInviteDataAttributes {
	this := ReplyToInviteDataAttributes{}
	this.Reply = reply
	return &this
}

// NewReplyToInviteDataAttributesWithDefaults instantiates a new ReplyToInviteDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplyToInviteDataAttributesWithDefaults() *ReplyToInviteDataAttributes {
	this := ReplyToInviteDataAttributes{}
	return &this
}

// GetReply returns the Reply field value
func (o *ReplyToInviteDataAttributes) GetReply() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reply
}

// GetReplyOk returns a tuple with the Reply field value
// and a boolean to check if the value has been set.
func (o *ReplyToInviteDataAttributes) GetReplyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reply, true
}

// SetReply sets field value
func (o *ReplyToInviteDataAttributes) SetReply(v string) {
	o.Reply = v
}

func (o ReplyToInviteDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReplyToInviteDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reply"] = o.Reply
	return toSerialize, nil
}

func (o *ReplyToInviteDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reply",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReplyToInviteDataAttributes := _ReplyToInviteDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReplyToInviteDataAttributes)

	if err != nil {
		return err
	}

	*o = ReplyToInviteDataAttributes(varReplyToInviteDataAttributes)

	return err
}

type NullableReplyToInviteDataAttributes struct {
	value *ReplyToInviteDataAttributes
	isSet bool
}

func (v NullableReplyToInviteDataAttributes) Get() *ReplyToInviteDataAttributes {
	return v.value
}

func (v *NullableReplyToInviteDataAttributes) Set(val *ReplyToInviteDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableReplyToInviteDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableReplyToInviteDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplyToInviteDataAttributes(val *ReplyToInviteDataAttributes) *NullableReplyToInviteDataAttributes {
	return &NullableReplyToInviteDataAttributes{value: val, isSet: true}
}

func (v NullableReplyToInviteDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplyToInviteDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


