/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEmployeeInvite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEmployeeInvite{}

// CreateEmployeeInvite struct for CreateEmployeeInvite
type CreateEmployeeInvite struct {
	Data CreateEmployeeInviteData `json:"data"`
}

type _CreateEmployeeInvite CreateEmployeeInvite

// NewCreateEmployeeInvite instantiates a new CreateEmployeeInvite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEmployeeInvite(data CreateEmployeeInviteData) *CreateEmployeeInvite {
	this := CreateEmployeeInvite{}
	this.Data = data
	return &this
}

// NewCreateEmployeeInviteWithDefaults instantiates a new CreateEmployeeInvite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEmployeeInviteWithDefaults() *CreateEmployeeInvite {
	this := CreateEmployeeInvite{}
	return &this
}

// GetData returns the Data field value
func (o *CreateEmployeeInvite) GetData() CreateEmployeeInviteData {
	if o == nil {
		var ret CreateEmployeeInviteData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateEmployeeInvite) GetDataOk() (*CreateEmployeeInviteData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateEmployeeInvite) SetData(v CreateEmployeeInviteData) {
	o.Data = v
}

func (o CreateEmployeeInvite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEmployeeInvite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateEmployeeInvite) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEmployeeInvite := _CreateEmployeeInvite{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEmployeeInvite)

	if err != nil {
		return err
	}

	*o = CreateEmployeeInvite(varCreateEmployeeInvite)

	return err
}

type NullableCreateEmployeeInvite struct {
	value *CreateEmployeeInvite
	isSet bool
}

func (v NullableCreateEmployeeInvite) Get() *CreateEmployeeInvite {
	return v.value
}

func (v *NullableCreateEmployeeInvite) Set(val *CreateEmployeeInvite) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEmployeeInvite) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEmployeeInvite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEmployeeInvite(val *CreateEmployeeInvite) *NullableCreateEmployeeInvite {
	return &NullableCreateEmployeeInvite{value: val, isSet: true}
}

func (v NullableCreateEmployeeInvite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEmployeeInvite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


