/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorBlocksCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorBlocksCollection{}

// DistributorBlocksCollection struct for DistributorBlocksCollection
type DistributorBlocksCollection struct {
	Data []DistributorBlockData `json:"data"`
	Links PaginationData `json:"links"`
}

type _DistributorBlocksCollection DistributorBlocksCollection

// NewDistributorBlocksCollection instantiates a new DistributorBlocksCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorBlocksCollection(data []DistributorBlockData, links PaginationData) *DistributorBlocksCollection {
	this := DistributorBlocksCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewDistributorBlocksCollectionWithDefaults instantiates a new DistributorBlocksCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorBlocksCollectionWithDefaults() *DistributorBlocksCollection {
	this := DistributorBlocksCollection{}
	return &this
}

// GetData returns the Data field value
func (o *DistributorBlocksCollection) GetData() []DistributorBlockData {
	if o == nil {
		var ret []DistributorBlockData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DistributorBlocksCollection) GetDataOk() ([]DistributorBlockData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *DistributorBlocksCollection) SetData(v []DistributorBlockData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *DistributorBlocksCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *DistributorBlocksCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *DistributorBlocksCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o DistributorBlocksCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorBlocksCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *DistributorBlocksCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorBlocksCollection := _DistributorBlocksCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorBlocksCollection)

	if err != nil {
		return err
	}

	*o = DistributorBlocksCollection(varDistributorBlocksCollection)

	return err
}

type NullableDistributorBlocksCollection struct {
	value *DistributorBlocksCollection
	isSet bool
}

func (v NullableDistributorBlocksCollection) Get() *DistributorBlocksCollection {
	return v.value
}

func (v *NullableDistributorBlocksCollection) Set(val *DistributorBlocksCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorBlocksCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorBlocksCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorBlocksCollection(val *DistributorBlocksCollection) *NullableDistributorBlocksCollection {
	return &NullableDistributorBlocksCollection{value: val, isSet: true}
}

func (v NullableDistributorBlocksCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorBlocksCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


