/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateDistributorDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDistributorDataAttributes{}

// UpdateDistributorDataAttributes struct for UpdateDistributorDataAttributes
type UpdateDistributorDataAttributes struct {
	// URL to the distributor's icon image.
	Icon *string `json:"icon,omitempty"`
	// The name of the distributor.
	Name *string `json:"name,omitempty"`
}

// NewUpdateDistributorDataAttributes instantiates a new UpdateDistributorDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDistributorDataAttributes() *UpdateDistributorDataAttributes {
	this := UpdateDistributorDataAttributes{}
	return &this
}

// NewUpdateDistributorDataAttributesWithDefaults instantiates a new UpdateDistributorDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDistributorDataAttributesWithDefaults() *UpdateDistributorDataAttributes {
	this := UpdateDistributorDataAttributes{}
	return &this
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *UpdateDistributorDataAttributes) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDistributorDataAttributes) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *UpdateDistributorDataAttributes) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *UpdateDistributorDataAttributes) SetIcon(v string) {
	o.Icon = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateDistributorDataAttributes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDistributorDataAttributes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateDistributorDataAttributes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateDistributorDataAttributes) SetName(v string) {
	o.Name = &v
}

func (o UpdateDistributorDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDistributorDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableUpdateDistributorDataAttributes struct {
	value *UpdateDistributorDataAttributes
	isSet bool
}

func (v NullableUpdateDistributorDataAttributes) Get() *UpdateDistributorDataAttributes {
	return v.value
}

func (v *NullableUpdateDistributorDataAttributes) Set(val *UpdateDistributorDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDistributorDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDistributorDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDistributorDataAttributes(val *UpdateDistributorDataAttributes) *NullableUpdateDistributorDataAttributes {
	return &NullableUpdateDistributorDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateDistributorDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDistributorDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


