/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the CompanyBlockData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyBlockData{}

// CompanyBlockData struct for CompanyBlockData
type CompanyBlockData struct {
	// company block id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes CompanyBlockAttributes `json:"attributes"`
}

type _CompanyBlockData CompanyBlockData

// NewCompanyBlockData instantiates a new CompanyBlockData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyBlockData(id uuid.UUID, type_ string, attributes CompanyBlockAttributes) *CompanyBlockData {
	this := CompanyBlockData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCompanyBlockDataWithDefaults instantiates a new CompanyBlockData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyBlockDataWithDefaults() *CompanyBlockData {
	this := CompanyBlockData{}
	return &this
}

// GetId returns the Id field value
func (o *CompanyBlockData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CompanyBlockData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CompanyBlockData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CompanyBlockData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CompanyBlockData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CompanyBlockData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CompanyBlockData) GetAttributes() CompanyBlockAttributes {
	if o == nil {
		var ret CompanyBlockAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CompanyBlockData) GetAttributesOk() (*CompanyBlockAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CompanyBlockData) SetAttributes(v CompanyBlockAttributes) {
	o.Attributes = v
}

func (o CompanyBlockData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyBlockData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CompanyBlockData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompanyBlockData := _CompanyBlockData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompanyBlockData)

	if err != nil {
		return err
	}

	*o = CompanyBlockData(varCompanyBlockData)

	return err
}

type NullableCompanyBlockData struct {
	value *CompanyBlockData
	isSet bool
}

func (v NullableCompanyBlockData) Get() *CompanyBlockData {
	return v.value
}

func (v *NullableCompanyBlockData) Set(val *CompanyBlockData) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyBlockData) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyBlockData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyBlockData(val *CompanyBlockData) *NullableCompanyBlockData {
	return &NullableCompanyBlockData{value: val, isSet: true}
}

func (v NullableCompanyBlockData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyBlockData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


