/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdateCompanyStatusData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCompanyStatusData{}

// UpdateCompanyStatusData struct for UpdateCompanyStatusData
type UpdateCompanyStatusData struct {
	// The UUID of the company to be updated.
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes UpdateCompanyStatusDataAttributes `json:"attributes"`
}

type _UpdateCompanyStatusData UpdateCompanyStatusData

// NewUpdateCompanyStatusData instantiates a new UpdateCompanyStatusData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCompanyStatusData(id uuid.UUID, type_ string, attributes UpdateCompanyStatusDataAttributes) *UpdateCompanyStatusData {
	this := UpdateCompanyStatusData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdateCompanyStatusDataWithDefaults instantiates a new UpdateCompanyStatusData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCompanyStatusDataWithDefaults() *UpdateCompanyStatusData {
	this := UpdateCompanyStatusData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateCompanyStatusData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateCompanyStatusData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateCompanyStatusData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdateCompanyStatusData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateCompanyStatusData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateCompanyStatusData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdateCompanyStatusData) GetAttributes() UpdateCompanyStatusDataAttributes {
	if o == nil {
		var ret UpdateCompanyStatusDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdateCompanyStatusData) GetAttributesOk() (*UpdateCompanyStatusDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdateCompanyStatusData) SetAttributes(v UpdateCompanyStatusDataAttributes) {
	o.Attributes = v
}

func (o UpdateCompanyStatusData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCompanyStatusData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdateCompanyStatusData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCompanyStatusData := _UpdateCompanyStatusData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCompanyStatusData)

	if err != nil {
		return err
	}

	*o = UpdateCompanyStatusData(varUpdateCompanyStatusData)

	return err
}

type NullableUpdateCompanyStatusData struct {
	value *UpdateCompanyStatusData
	isSet bool
}

func (v NullableUpdateCompanyStatusData) Get() *UpdateCompanyStatusData {
	return v.value
}

func (v *NullableUpdateCompanyStatusData) Set(val *UpdateCompanyStatusData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCompanyStatusData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCompanyStatusData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCompanyStatusData(val *UpdateCompanyStatusData) *NullableUpdateCompanyStatusData {
	return &NullableUpdateCompanyStatusData{value: val, isSet: true}
}

func (v NullableUpdateCompanyStatusData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCompanyStatusData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


