/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDistributorBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDistributorBlock{}

// CreateDistributorBlock struct for CreateDistributorBlock
type CreateDistributorBlock struct {
	Data CreateDistributorBlockData `json:"data"`
}

type _CreateDistributorBlock CreateDistributorBlock

// NewCreateDistributorBlock instantiates a new CreateDistributorBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDistributorBlock(data CreateDistributorBlockData) *CreateDistributorBlock {
	this := CreateDistributorBlock{}
	this.Data = data
	return &this
}

// NewCreateDistributorBlockWithDefaults instantiates a new CreateDistributorBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDistributorBlockWithDefaults() *CreateDistributorBlock {
	this := CreateDistributorBlock{}
	return &this
}

// GetData returns the Data field value
func (o *CreateDistributorBlock) GetData() CreateDistributorBlockData {
	if o == nil {
		var ret CreateDistributorBlockData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateDistributorBlock) GetDataOk() (*CreateDistributorBlockData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateDistributorBlock) SetData(v CreateDistributorBlockData) {
	o.Data = v
}

func (o CreateDistributorBlock) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDistributorBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateDistributorBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDistributorBlock := _CreateDistributorBlock{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDistributorBlock)

	if err != nil {
		return err
	}

	*o = CreateDistributorBlock(varCreateDistributorBlock)

	return err
}

type NullableCreateDistributorBlock struct {
	value *CreateDistributorBlock
	isSet bool
}

func (v NullableCreateDistributorBlock) Get() *CreateDistributorBlock {
	return v.value
}

func (v *NullableCreateDistributorBlock) Set(val *CreateDistributorBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDistributorBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDistributorBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDistributorBlock(val *CreateDistributorBlock) *NullableCreateDistributorBlock {
	return &NullableCreateDistributorBlock{value: val, isSet: true}
}

func (v NullableCreateDistributorBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDistributorBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


