/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateDistributorStatusDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDistributorStatusDataAttributes{}

// UpdateDistributorStatusDataAttributes struct for UpdateDistributorStatusDataAttributes
type UpdateDistributorStatusDataAttributes struct {
	// The new status of the distributor.
	Status string `json:"status"`
}

type _UpdateDistributorStatusDataAttributes UpdateDistributorStatusDataAttributes

// NewUpdateDistributorStatusDataAttributes instantiates a new UpdateDistributorStatusDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDistributorStatusDataAttributes(status string) *UpdateDistributorStatusDataAttributes {
	this := UpdateDistributorStatusDataAttributes{}
	this.Status = status
	return &this
}

// NewUpdateDistributorStatusDataAttributesWithDefaults instantiates a new UpdateDistributorStatusDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDistributorStatusDataAttributesWithDefaults() *UpdateDistributorStatusDataAttributes {
	this := UpdateDistributorStatusDataAttributes{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateDistributorStatusDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateDistributorStatusDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateDistributorStatusDataAttributes) SetStatus(v string) {
	o.Status = v
}

func (o UpdateDistributorStatusDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDistributorStatusDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateDistributorStatusDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDistributorStatusDataAttributes := _UpdateDistributorStatusDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateDistributorStatusDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdateDistributorStatusDataAttributes(varUpdateDistributorStatusDataAttributes)

	return err
}

type NullableUpdateDistributorStatusDataAttributes struct {
	value *UpdateDistributorStatusDataAttributes
	isSet bool
}

func (v NullableUpdateDistributorStatusDataAttributes) Get() *UpdateDistributorStatusDataAttributes {
	return v.value
}

func (v *NullableUpdateDistributorStatusDataAttributes) Set(val *UpdateDistributorStatusDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDistributorStatusDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDistributorStatusDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDistributorStatusDataAttributes(val *UpdateDistributorStatusDataAttributes) *NullableUpdateDistributorStatusDataAttributes {
	return &NullableUpdateDistributorStatusDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateDistributorStatusDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDistributorStatusDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


