/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UpdateEmployeeDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEmployeeDataAttributes{}

// UpdateEmployeeDataAttributes struct for UpdateEmployeeDataAttributes
type UpdateEmployeeDataAttributes struct {
	// The role or position of the employee within the company.
	Role *string `json:"role,omitempty"`
	// The job title of the employee.
	Position *string `json:"position,omitempty"`
	// A label or tag associated with the employee.
	Label *string `json:"label,omitempty"`
}

// NewUpdateEmployeeDataAttributes instantiates a new UpdateEmployeeDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEmployeeDataAttributes() *UpdateEmployeeDataAttributes {
	this := UpdateEmployeeDataAttributes{}
	return &this
}

// NewUpdateEmployeeDataAttributesWithDefaults instantiates a new UpdateEmployeeDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEmployeeDataAttributesWithDefaults() *UpdateEmployeeDataAttributes {
	this := UpdateEmployeeDataAttributes{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *UpdateEmployeeDataAttributes) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmployeeDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *UpdateEmployeeDataAttributes) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *UpdateEmployeeDataAttributes) SetRole(v string) {
	o.Role = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *UpdateEmployeeDataAttributes) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmployeeDataAttributes) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *UpdateEmployeeDataAttributes) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *UpdateEmployeeDataAttributes) SetPosition(v string) {
	o.Position = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *UpdateEmployeeDataAttributes) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateEmployeeDataAttributes) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *UpdateEmployeeDataAttributes) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *UpdateEmployeeDataAttributes) SetLabel(v string) {
	o.Label = &v
}

func (o UpdateEmployeeDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEmployeeDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableUpdateEmployeeDataAttributes struct {
	value *UpdateEmployeeDataAttributes
	isSet bool
}

func (v NullableUpdateEmployeeDataAttributes) Get() *UpdateEmployeeDataAttributes {
	return v.value
}

func (v *NullableUpdateEmployeeDataAttributes) Set(val *UpdateEmployeeDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEmployeeDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEmployeeDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEmployeeDataAttributes(val *UpdateEmployeeDataAttributes) *NullableUpdateEmployeeDataAttributes {
	return &NullableUpdateEmployeeDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateEmployeeDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEmployeeDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


