/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDistributorDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDistributorDataAttributes{}

// CreateDistributorDataAttributes struct for CreateDistributorDataAttributes
type CreateDistributorDataAttributes struct {
	// URL to the distributor's icon image.
	Icon string `json:"icon"`
	// The name of the distributor.
	Name string `json:"name"`
}

type _CreateDistributorDataAttributes CreateDistributorDataAttributes

// NewCreateDistributorDataAttributes instantiates a new CreateDistributorDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDistributorDataAttributes(icon string, name string) *CreateDistributorDataAttributes {
	this := CreateDistributorDataAttributes{}
	this.Icon = icon
	this.Name = name
	return &this
}

// NewCreateDistributorDataAttributesWithDefaults instantiates a new CreateDistributorDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDistributorDataAttributesWithDefaults() *CreateDistributorDataAttributes {
	this := CreateDistributorDataAttributes{}
	return &this
}

// GetIcon returns the Icon field value
func (o *CreateDistributorDataAttributes) GetIcon() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Icon
}

// GetIconOk returns a tuple with the Icon field value
// and a boolean to check if the value has been set.
func (o *CreateDistributorDataAttributes) GetIconOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icon, true
}

// SetIcon sets field value
func (o *CreateDistributorDataAttributes) SetIcon(v string) {
	o.Icon = v
}

// GetName returns the Name field value
func (o *CreateDistributorDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateDistributorDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateDistributorDataAttributes) SetName(v string) {
	o.Name = v
}

func (o CreateDistributorDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDistributorDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["icon"] = o.Icon
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateDistributorDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"icon",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDistributorDataAttributes := _CreateDistributorDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDistributorDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateDistributorDataAttributes(varCreateDistributorDataAttributes)

	return err
}

type NullableCreateDistributorDataAttributes struct {
	value *CreateDistributorDataAttributes
	isSet bool
}

func (v NullableCreateDistributorDataAttributes) Get() *CreateDistributorDataAttributes {
	return v.value
}

func (v *NullableCreateDistributorDataAttributes) Set(val *CreateDistributorDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDistributorDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDistributorDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDistributorDataAttributes(val *CreateDistributorDataAttributes) *NullableCreateDistributorDataAttributes {
	return &NullableCreateDistributorDataAttributes{value: val, isSet: true}
}

func (v NullableCreateDistributorDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDistributorDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


