/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDistributor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDistributor{}

// CreateDistributor struct for CreateDistributor
type CreateDistributor struct {
	Data CreateDistributorData `json:"data"`
}

type _CreateDistributor CreateDistributor

// NewCreateDistributor instantiates a new CreateDistributor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDistributor(data CreateDistributorData) *CreateDistributor {
	this := CreateDistributor{}
	this.Data = data
	return &this
}

// NewCreateDistributorWithDefaults instantiates a new CreateDistributor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDistributorWithDefaults() *CreateDistributor {
	this := CreateDistributor{}
	return &this
}

// GetData returns the Data field value
func (o *CreateDistributor) GetData() CreateDistributorData {
	if o == nil {
		var ret CreateDistributorData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateDistributor) GetDataOk() (*CreateDistributorData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateDistributor) SetData(v CreateDistributorData) {
	o.Data = v
}

func (o CreateDistributor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDistributor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateDistributor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDistributor := _CreateDistributor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDistributor)

	if err != nil {
		return err
	}

	*o = CreateDistributor(varCreateDistributor)

	return err
}

type NullableCreateDistributor struct {
	value *CreateDistributor
	isSet bool
}

func (v NullableCreateDistributor) Get() *CreateDistributor {
	return v.value
}

func (v *NullableCreateDistributor) Set(val *CreateDistributor) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDistributor) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDistributor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDistributor(val *CreateDistributor) *NullableCreateDistributor {
	return &NullableCreateDistributor{value: val, isSet: true}
}

func (v NullableCreateDistributor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDistributor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


