/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEmployeeInviteDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEmployeeInviteDataAttributes{}

// CreateEmployeeInviteDataAttributes struct for CreateEmployeeInviteDataAttributes
type CreateEmployeeInviteDataAttributes struct {
	// The UUID of the distributor to which the user is being invited.
	DistributorId string `json:"distributor_id"`
	// The UUID of the user being invited.
	UserId string `json:"user_id"`
	// The role assigned to the invited user within the distributor.
	Role string `json:"role"`
}

type _CreateEmployeeInviteDataAttributes CreateEmployeeInviteDataAttributes

// NewCreateEmployeeInviteDataAttributes instantiates a new CreateEmployeeInviteDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEmployeeInviteDataAttributes(distributorId string, userId string, role string) *CreateEmployeeInviteDataAttributes {
	this := CreateEmployeeInviteDataAttributes{}
	this.DistributorId = distributorId
	this.UserId = userId
	this.Role = role
	return &this
}

// NewCreateEmployeeInviteDataAttributesWithDefaults instantiates a new CreateEmployeeInviteDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEmployeeInviteDataAttributesWithDefaults() *CreateEmployeeInviteDataAttributes {
	this := CreateEmployeeInviteDataAttributes{}
	return &this
}

// GetDistributorId returns the DistributorId field value
func (o *CreateEmployeeInviteDataAttributes) GetDistributorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DistributorId
}

// GetDistributorIdOk returns a tuple with the DistributorId field value
// and a boolean to check if the value has been set.
func (o *CreateEmployeeInviteDataAttributes) GetDistributorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DistributorId, true
}

// SetDistributorId sets field value
func (o *CreateEmployeeInviteDataAttributes) SetDistributorId(v string) {
	o.DistributorId = v
}

// GetUserId returns the UserId field value
func (o *CreateEmployeeInviteDataAttributes) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *CreateEmployeeInviteDataAttributes) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *CreateEmployeeInviteDataAttributes) SetUserId(v string) {
	o.UserId = v
}

// GetRole returns the Role field value
func (o *CreateEmployeeInviteDataAttributes) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *CreateEmployeeInviteDataAttributes) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *CreateEmployeeInviteDataAttributes) SetRole(v string) {
	o.Role = v
}

func (o CreateEmployeeInviteDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEmployeeInviteDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["distributor_id"] = o.DistributorId
	toSerialize["user_id"] = o.UserId
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *CreateEmployeeInviteDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"distributor_id",
		"user_id",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEmployeeInviteDataAttributes := _CreateEmployeeInviteDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEmployeeInviteDataAttributes)

	if err != nil {
		return err
	}

	*o = CreateEmployeeInviteDataAttributes(varCreateEmployeeInviteDataAttributes)

	return err
}

type NullableCreateEmployeeInviteDataAttributes struct {
	value *CreateEmployeeInviteDataAttributes
	isSet bool
}

func (v NullableCreateEmployeeInviteDataAttributes) Get() *CreateEmployeeInviteDataAttributes {
	return v.value
}

func (v *NullableCreateEmployeeInviteDataAttributes) Set(val *CreateEmployeeInviteDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEmployeeInviteDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEmployeeInviteDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEmployeeInviteDataAttributes(val *CreateEmployeeInviteDataAttributes) *NullableCreateEmployeeInviteDataAttributes {
	return &NullableCreateEmployeeInviteDataAttributes{value: val, isSet: true}
}

func (v NullableCreateEmployeeInviteDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEmployeeInviteDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


