/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmployeesCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmployeesCollection{}

// EmployeesCollection struct for EmployeesCollection
type EmployeesCollection struct {
	Data []EmployeeData `json:"data"`
	Links PaginationData `json:"links"`
}

type _EmployeesCollection EmployeesCollection

// NewEmployeesCollection instantiates a new EmployeesCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmployeesCollection(data []EmployeeData, links PaginationData) *EmployeesCollection {
	this := EmployeesCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewEmployeesCollectionWithDefaults instantiates a new EmployeesCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmployeesCollectionWithDefaults() *EmployeesCollection {
	this := EmployeesCollection{}
	return &this
}

// GetData returns the Data field value
func (o *EmployeesCollection) GetData() []EmployeeData {
	if o == nil {
		var ret []EmployeeData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *EmployeesCollection) GetDataOk() ([]EmployeeData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *EmployeesCollection) SetData(v []EmployeeData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *EmployeesCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *EmployeesCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *EmployeesCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o EmployeesCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmployeesCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *EmployeesCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmployeesCollection := _EmployeesCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmployeesCollection)

	if err != nil {
		return err
	}

	*o = EmployeesCollection(varEmployeesCollection)

	return err
}

type NullableEmployeesCollection struct {
	value *EmployeesCollection
	isSet bool
}

func (v NullableEmployeesCollection) Get() *EmployeesCollection {
	return v.value
}

func (v *NullableEmployeesCollection) Set(val *EmployeesCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeesCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeesCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeesCollection(val *EmployeesCollection) *NullableEmployeesCollection {
	return &NullableEmployeesCollection{value: val, isSet: true}
}

func (v NullableEmployeesCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeesCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


