/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorsCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorsCollection{}

// DistributorsCollection struct for DistributorsCollection
type DistributorsCollection struct {
	Data []DistributorData `json:"data"`
	Links PaginationData `json:"links"`
}

type _DistributorsCollection DistributorsCollection

// NewDistributorsCollection instantiates a new DistributorsCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorsCollection(data []DistributorData, links PaginationData) *DistributorsCollection {
	this := DistributorsCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewDistributorsCollectionWithDefaults instantiates a new DistributorsCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorsCollectionWithDefaults() *DistributorsCollection {
	this := DistributorsCollection{}
	return &this
}

// GetData returns the Data field value
func (o *DistributorsCollection) GetData() []DistributorData {
	if o == nil {
		var ret []DistributorData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DistributorsCollection) GetDataOk() ([]DistributorData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *DistributorsCollection) SetData(v []DistributorData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *DistributorsCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *DistributorsCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *DistributorsCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o DistributorsCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorsCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *DistributorsCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorsCollection := _DistributorsCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorsCollection)

	if err != nil {
		return err
	}

	*o = DistributorsCollection(varDistributorsCollection)

	return err
}

type NullableDistributorsCollection struct {
	value *DistributorsCollection
	isSet bool
}

func (v NullableDistributorsCollection) Get() *DistributorsCollection {
	return v.value
}

func (v *NullableDistributorsCollection) Set(val *DistributorsCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorsCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorsCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorsCollection(val *DistributorsCollection) *NullableDistributorsCollection {
	return &NullableDistributorsCollection{value: val, isSet: true}
}

func (v NullableDistributorsCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorsCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


