/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateDistributorStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDistributorStatus{}

// UpdateDistributorStatus struct for UpdateDistributorStatus
type UpdateDistributorStatus struct {
	Data UpdateDistributorStatusData `json:"data"`
}

type _UpdateDistributorStatus UpdateDistributorStatus

// NewUpdateDistributorStatus instantiates a new UpdateDistributorStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDistributorStatus(data UpdateDistributorStatusData) *UpdateDistributorStatus {
	this := UpdateDistributorStatus{}
	this.Data = data
	return &this
}

// NewUpdateDistributorStatusWithDefaults instantiates a new UpdateDistributorStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDistributorStatusWithDefaults() *UpdateDistributorStatus {
	this := UpdateDistributorStatus{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateDistributorStatus) GetData() UpdateDistributorStatusData {
	if o == nil {
		var ret UpdateDistributorStatusData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateDistributorStatus) GetDataOk() (*UpdateDistributorStatusData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateDistributorStatus) SetData(v UpdateDistributorStatusData) {
	o.Data = v
}

func (o UpdateDistributorStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDistributorStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateDistributorStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDistributorStatus := _UpdateDistributorStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateDistributorStatus)

	if err != nil {
		return err
	}

	*o = UpdateDistributorStatus(varUpdateDistributorStatus)

	return err
}

type NullableUpdateDistributorStatus struct {
	value *UpdateDistributorStatus
	isSet bool
}

func (v NullableUpdateDistributorStatus) Get() *UpdateDistributorStatus {
	return v.value
}

func (v *NullableUpdateDistributorStatus) Set(val *UpdateDistributorStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDistributorStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDistributorStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDistributorStatus(val *UpdateDistributorStatus) *NullableUpdateDistributorStatus {
	return &NullableUpdateDistributorStatus{value: val, isSet: true}
}

func (v NullableUpdateDistributorStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDistributorStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


