/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the AnswerInviteData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnswerInviteData{}

// AnswerInviteData struct for AnswerInviteData
type AnswerInviteData struct {
	// invite id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes AnswerInviteDataAttributes `json:"attributes"`
}

type _AnswerInviteData AnswerInviteData

// NewAnswerInviteData instantiates a new AnswerInviteData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnswerInviteData(id uuid.UUID, type_ string, attributes AnswerInviteDataAttributes) *AnswerInviteData {
	this := AnswerInviteData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewAnswerInviteDataWithDefaults instantiates a new AnswerInviteData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnswerInviteDataWithDefaults() *AnswerInviteData {
	this := AnswerInviteData{}
	return &this
}

// GetId returns the Id field value
func (o *AnswerInviteData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AnswerInviteData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AnswerInviteData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *AnswerInviteData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AnswerInviteData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AnswerInviteData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *AnswerInviteData) GetAttributes() AnswerInviteDataAttributes {
	if o == nil {
		var ret AnswerInviteDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *AnswerInviteData) GetAttributesOk() (*AnswerInviteDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *AnswerInviteData) SetAttributes(v AnswerInviteDataAttributes) {
	o.Attributes = v
}

func (o AnswerInviteData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnswerInviteData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *AnswerInviteData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnswerInviteData := _AnswerInviteData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnswerInviteData)

	if err != nil {
		return err
	}

	*o = AnswerInviteData(varAnswerInviteData)

	return err
}

type NullableAnswerInviteData struct {
	value *AnswerInviteData
	isSet bool
}

func (v NullableAnswerInviteData) Get() *AnswerInviteData {
	return v.value
}

func (v *NullableAnswerInviteData) Set(val *AnswerInviteData) {
	v.value = val
	v.isSet = true
}

func (v NullableAnswerInviteData) IsSet() bool {
	return v.isSet
}

func (v *NullableAnswerInviteData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnswerInviteData(val *AnswerInviteData) *NullableAnswerInviteData {
	return &NullableAnswerInviteData{value: val, isSet: true}
}

func (v NullableAnswerInviteData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnswerInviteData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


