/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the CompanyData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyData{}

// CompanyData struct for CompanyData
type CompanyData struct {
	// company id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes CompanyAttributes `json:"attributes"`
}

type _CompanyData CompanyData

// NewCompanyData instantiates a new CompanyData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyData(id uuid.UUID, type_ string, attributes CompanyAttributes) *CompanyData {
	this := CompanyData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCompanyDataWithDefaults instantiates a new CompanyData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyDataWithDefaults() *CompanyData {
	this := CompanyData{}
	return &this
}

// GetId returns the Id field value
func (o *CompanyData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CompanyData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CompanyData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *CompanyData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CompanyData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CompanyData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CompanyData) GetAttributes() CompanyAttributes {
	if o == nil {
		var ret CompanyAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CompanyData) GetAttributesOk() (*CompanyAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CompanyData) SetAttributes(v CompanyAttributes) {
	o.Attributes = v
}

func (o CompanyData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CompanyData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompanyData := _CompanyData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompanyData)

	if err != nil {
		return err
	}

	*o = CompanyData(varCompanyData)

	return err
}

type NullableCompanyData struct {
	value *CompanyData
	isSet bool
}

func (v NullableCompanyData) Get() *CompanyData {
	return v.value
}

func (v *NullableCompanyData) Set(val *CompanyData) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyData) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyData(val *CompanyData) *NullableCompanyData {
	return &NullableCompanyData{value: val, isSet: true}
}

func (v NullableCompanyData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


