/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DistributorBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributorBlock{}

// DistributorBlock struct for DistributorBlock
type DistributorBlock struct {
	Data DistributorBlockData `json:"data"`
}

type _DistributorBlock DistributorBlock

// NewDistributorBlock instantiates a new DistributorBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributorBlock(data DistributorBlockData) *DistributorBlock {
	this := DistributorBlock{}
	this.Data = data
	return &this
}

// NewDistributorBlockWithDefaults instantiates a new DistributorBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributorBlockWithDefaults() *DistributorBlock {
	this := DistributorBlock{}
	return &this
}

// GetData returns the Data field value
func (o *DistributorBlock) GetData() DistributorBlockData {
	if o == nil {
		var ret DistributorBlockData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DistributorBlock) GetDataOk() (*DistributorBlockData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DistributorBlock) SetData(v DistributorBlockData) {
	o.Data = v
}

func (o DistributorBlock) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributorBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DistributorBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDistributorBlock := _DistributorBlock{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDistributorBlock)

	if err != nil {
		return err
	}

	*o = DistributorBlock(varDistributorBlock)

	return err
}

type NullableDistributorBlock struct {
	value *DistributorBlock
	isSet bool
}

func (v NullableDistributorBlock) Get() *DistributorBlock {
	return v.value
}

func (v *NullableDistributorBlock) Set(val *DistributorBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributorBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributorBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributorBlock(val *DistributorBlock) *NullableDistributorBlock {
	return &NullableDistributorBlock{value: val, isSet: true}
}

func (v NullableDistributorBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributorBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


