/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEmployeeInviteData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEmployeeInviteData{}

// CreateEmployeeInviteData struct for CreateEmployeeInviteData
type CreateEmployeeInviteData struct {
	Type string `json:"type"`
	Attributes CreateEmployeeInviteDataAttributes `json:"attributes"`
}

type _CreateEmployeeInviteData CreateEmployeeInviteData

// NewCreateEmployeeInviteData instantiates a new CreateEmployeeInviteData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEmployeeInviteData(type_ string, attributes CreateEmployeeInviteDataAttributes) *CreateEmployeeInviteData {
	this := CreateEmployeeInviteData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateEmployeeInviteDataWithDefaults instantiates a new CreateEmployeeInviteData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEmployeeInviteDataWithDefaults() *CreateEmployeeInviteData {
	this := CreateEmployeeInviteData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateEmployeeInviteData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateEmployeeInviteData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateEmployeeInviteData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateEmployeeInviteData) GetAttributes() CreateEmployeeInviteDataAttributes {
	if o == nil {
		var ret CreateEmployeeInviteDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateEmployeeInviteData) GetAttributesOk() (*CreateEmployeeInviteDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateEmployeeInviteData) SetAttributes(v CreateEmployeeInviteDataAttributes) {
	o.Attributes = v
}

func (o CreateEmployeeInviteData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEmployeeInviteData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateEmployeeInviteData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEmployeeInviteData := _CreateEmployeeInviteData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEmployeeInviteData)

	if err != nil {
		return err
	}

	*o = CreateEmployeeInviteData(varCreateEmployeeInviteData)

	return err
}

type NullableCreateEmployeeInviteData struct {
	value *CreateEmployeeInviteData
	isSet bool
}

func (v NullableCreateEmployeeInviteData) Get() *CreateEmployeeInviteData {
	return v.value
}

func (v *NullableCreateEmployeeInviteData) Set(val *CreateEmployeeInviteData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEmployeeInviteData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEmployeeInviteData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEmployeeInviteData(val *CreateEmployeeInviteData) *NullableCreateEmployeeInviteData {
	return &NullableCreateEmployeeInviteData{value: val, isSet: true}
}

func (v NullableCreateEmployeeInviteData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEmployeeInviteData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


