/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AnswerInvite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnswerInvite{}

// AnswerInvite struct for AnswerInvite
type AnswerInvite struct {
	Data AnswerInviteData `json:"data"`
}

type _AnswerInvite AnswerInvite

// NewAnswerInvite instantiates a new AnswerInvite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnswerInvite(data AnswerInviteData) *AnswerInvite {
	this := AnswerInvite{}
	this.Data = data
	return &this
}

// NewAnswerInviteWithDefaults instantiates a new AnswerInvite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnswerInviteWithDefaults() *AnswerInvite {
	this := AnswerInvite{}
	return &this
}

// GetData returns the Data field value
func (o *AnswerInvite) GetData() AnswerInviteData {
	if o == nil {
		var ret AnswerInviteData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AnswerInvite) GetDataOk() (*AnswerInviteData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AnswerInvite) SetData(v AnswerInviteData) {
	o.Data = v
}

func (o AnswerInvite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnswerInvite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AnswerInvite) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnswerInvite := _AnswerInvite{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnswerInvite)

	if err != nil {
		return err
	}

	*o = AnswerInvite(varAnswerInvite)

	return err
}

type NullableAnswerInvite struct {
	value *AnswerInvite
	isSet bool
}

func (v NullableAnswerInvite) Get() *AnswerInvite {
	return v.value
}

func (v *NullableAnswerInvite) Set(val *AnswerInvite) {
	v.value = val
	v.isSet = true
}

func (v NullableAnswerInvite) IsSet() bool {
	return v.isSet
}

func (v *NullableAnswerInvite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnswerInvite(val *AnswerInvite) *NullableAnswerInvite {
	return &NullableAnswerInvite{value: val, isSet: true}
}

func (v NullableAnswerInvite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnswerInvite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


