/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateCompanyBlock type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCompanyBlock{}

// CreateCompanyBlock struct for CreateCompanyBlock
type CreateCompanyBlock struct {
	Data CreateCompanyBlockData `json:"data"`
}

type _CreateCompanyBlock CreateCompanyBlock

// NewCreateCompanyBlock instantiates a new CreateCompanyBlock object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCompanyBlock(data CreateCompanyBlockData) *CreateCompanyBlock {
	this := CreateCompanyBlock{}
	this.Data = data
	return &this
}

// NewCreateCompanyBlockWithDefaults instantiates a new CreateCompanyBlock object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCompanyBlockWithDefaults() *CreateCompanyBlock {
	this := CreateCompanyBlock{}
	return &this
}

// GetData returns the Data field value
func (o *CreateCompanyBlock) GetData() CreateCompanyBlockData {
	if o == nil {
		var ret CreateCompanyBlockData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateCompanyBlock) GetDataOk() (*CreateCompanyBlockData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateCompanyBlock) SetData(v CreateCompanyBlockData) {
	o.Data = v
}

func (o CreateCompanyBlock) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCompanyBlock) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreateCompanyBlock) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateCompanyBlock := _CreateCompanyBlock{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateCompanyBlock)

	if err != nil {
		return err
	}

	*o = CreateCompanyBlock(varCreateCompanyBlock)

	return err
}

type NullableCreateCompanyBlock struct {
	value *CreateCompanyBlock
	isSet bool
}

func (v NullableCreateCompanyBlock) Get() *CreateCompanyBlock {
	return v.value
}

func (v *NullableCreateCompanyBlock) Set(val *CreateCompanyBlock) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCompanyBlock) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCompanyBlock) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCompanyBlock(val *CreateCompanyBlock) *NullableCreateCompanyBlock {
	return &NullableCreateCompanyBlock{value: val, isSet: true}
}

func (v NullableCreateCompanyBlock) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCompanyBlock) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


