/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDistributorData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDistributorData{}

// CreateDistributorData struct for CreateDistributorData
type CreateDistributorData struct {
	Type string `json:"type"`
	Attributes CreateDistributorDataAttributes `json:"attributes"`
}

type _CreateDistributorData CreateDistributorData

// NewCreateDistributorData instantiates a new CreateDistributorData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDistributorData(type_ string, attributes CreateDistributorDataAttributes) *CreateDistributorData {
	this := CreateDistributorData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreateDistributorDataWithDefaults instantiates a new CreateDistributorData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDistributorDataWithDefaults() *CreateDistributorData {
	this := CreateDistributorData{}
	return &this
}

// GetType returns the Type field value
func (o *CreateDistributorData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateDistributorData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateDistributorData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreateDistributorData) GetAttributes() CreateDistributorDataAttributes {
	if o == nil {
		var ret CreateDistributorDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreateDistributorData) GetAttributesOk() (*CreateDistributorDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreateDistributorData) SetAttributes(v CreateDistributorDataAttributes) {
	o.Attributes = v
}

func (o CreateDistributorData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDistributorData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreateDistributorData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDistributorData := _CreateDistributorData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDistributorData)

	if err != nil {
		return err
	}

	*o = CreateDistributorData(varCreateDistributorData)

	return err
}

type NullableCreateDistributorData struct {
	value *CreateDistributorData
	isSet bool
}

func (v NullableCreateDistributorData) Get() *CreateDistributorData {
	return v.value
}

func (v *NullableCreateDistributorData) Set(val *CreateDistributorData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDistributorData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDistributorData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDistributorData(val *CreateDistributorData) *NullableCreateDistributorData {
	return &NullableCreateDistributorData{value: val, isSet: true}
}

func (v NullableCreateDistributorData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDistributorData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


