/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CompanyBlocksCollection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyBlocksCollection{}

// CompanyBlocksCollection struct for CompanyBlocksCollection
type CompanyBlocksCollection struct {
	Data []CompanyBlockData `json:"data"`
	Links PaginationData `json:"links"`
}

type _CompanyBlocksCollection CompanyBlocksCollection

// NewCompanyBlocksCollection instantiates a new CompanyBlocksCollection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyBlocksCollection(data []CompanyBlockData, links PaginationData) *CompanyBlocksCollection {
	this := CompanyBlocksCollection{}
	this.Data = data
	this.Links = links
	return &this
}

// NewCompanyBlocksCollectionWithDefaults instantiates a new CompanyBlocksCollection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyBlocksCollectionWithDefaults() *CompanyBlocksCollection {
	this := CompanyBlocksCollection{}
	return &this
}

// GetData returns the Data field value
func (o *CompanyBlocksCollection) GetData() []CompanyBlockData {
	if o == nil {
		var ret []CompanyBlockData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CompanyBlocksCollection) GetDataOk() ([]CompanyBlockData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CompanyBlocksCollection) SetData(v []CompanyBlockData) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *CompanyBlocksCollection) GetLinks() PaginationData {
	if o == nil {
		var ret PaginationData
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *CompanyBlocksCollection) GetLinksOk() (*PaginationData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *CompanyBlocksCollection) SetLinks(v PaginationData) {
	o.Links = v
}

func (o CompanyBlocksCollection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyBlocksCollection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *CompanyBlocksCollection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCompanyBlocksCollection := _CompanyBlocksCollection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCompanyBlocksCollection)

	if err != nil {
		return err
	}

	*o = CompanyBlocksCollection(varCompanyBlocksCollection)

	return err
}

type NullableCompanyBlocksCollection struct {
	value *CompanyBlocksCollection
	isSet bool
}

func (v NullableCompanyBlocksCollection) Get() *CompanyBlocksCollection {
	return v.value
}

func (v *NullableCompanyBlocksCollection) Set(val *CompanyBlocksCollection) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyBlocksCollection) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyBlocksCollection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyBlocksCollection(val *CompanyBlocksCollection) *NullableCompanyBlocksCollection {
	return &NullableCompanyBlocksCollection{value: val, isSet: true}
}

func (v NullableCompanyBlocksCollection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyBlocksCollection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


