/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateDistributor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDistributor{}

// UpdateDistributor struct for UpdateDistributor
type UpdateDistributor struct {
	Data UpdateDistributorData `json:"data"`
}

type _UpdateDistributor UpdateDistributor

// NewUpdateDistributor instantiates a new UpdateDistributor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDistributor(data UpdateDistributorData) *UpdateDistributor {
	this := UpdateDistributor{}
	this.Data = data
	return &this
}

// NewUpdateDistributorWithDefaults instantiates a new UpdateDistributor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDistributorWithDefaults() *UpdateDistributor {
	this := UpdateDistributor{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateDistributor) GetData() UpdateDistributorData {
	if o == nil {
		var ret UpdateDistributorData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateDistributor) GetDataOk() (*UpdateDistributorData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateDistributor) SetData(v UpdateDistributorData) {
	o.Data = v
}

func (o UpdateDistributor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDistributor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdateDistributor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDistributor := _UpdateDistributor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateDistributor)

	if err != nil {
		return err
	}

	*o = UpdateDistributor(varUpdateDistributor)

	return err
}

type NullableUpdateDistributor struct {
	value *UpdateDistributor
	isSet bool
}

func (v NullableUpdateDistributor) Get() *UpdateDistributor {
	return v.value
}

func (v *NullableUpdateDistributor) Set(val *UpdateDistributor) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDistributor) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDistributor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDistributor(val *UpdateDistributor) *NullableUpdateDistributor {
	return &NullableUpdateDistributor{value: val, isSet: true}
}

func (v NullableUpdateDistributor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDistributor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


