/*
Cifra SSO REST API

SSO REST API for Cifra app

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the ReplyToInviteData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReplyToInviteData{}

// ReplyToInviteData struct for ReplyToInviteData
type ReplyToInviteData struct {
	// invite id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes ReplyToInviteDataAttributes `json:"attributes"`
}

type _ReplyToInviteData ReplyToInviteData

// NewReplyToInviteData instantiates a new ReplyToInviteData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplyToInviteData(id uuid.UUID, type_ string, attributes ReplyToInviteDataAttributes) *ReplyToInviteData {
	this := ReplyToInviteData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewReplyToInviteDataWithDefaults instantiates a new ReplyToInviteData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplyToInviteDataWithDefaults() *ReplyToInviteData {
	this := ReplyToInviteData{}
	return &this
}

// GetId returns the Id field value
func (o *ReplyToInviteData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ReplyToInviteData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ReplyToInviteData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ReplyToInviteData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ReplyToInviteData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ReplyToInviteData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ReplyToInviteData) GetAttributes() ReplyToInviteDataAttributes {
	if o == nil {
		var ret ReplyToInviteDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ReplyToInviteData) GetAttributesOk() (*ReplyToInviteDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ReplyToInviteData) SetAttributes(v ReplyToInviteDataAttributes) {
	o.Attributes = v
}

func (o ReplyToInviteData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReplyToInviteData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ReplyToInviteData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReplyToInviteData := _ReplyToInviteData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReplyToInviteData)

	if err != nil {
		return err
	}

	*o = ReplyToInviteData(varReplyToInviteData)

	return err
}

type NullableReplyToInviteData struct {
	value *ReplyToInviteData
	isSet bool
}

func (v NullableReplyToInviteData) Get() *ReplyToInviteData {
	return v.value
}

func (v *NullableReplyToInviteData) Set(val *ReplyToInviteData) {
	v.value = val
	v.isSet = true
}

func (v NullableReplyToInviteData) IsSet() bool {
	return v.isSet
}

func (v *NullableReplyToInviteData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplyToInviteData(val *ReplyToInviteData) *NullableReplyToInviteData {
	return &NullableReplyToInviteData{value: val, isSet: true}
}

func (v NullableReplyToInviteData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplyToInviteData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


