openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    CreateDistributor:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - create_distributor
            attributes:
              type: object
              required:
                - icon
                - name
              properties:
                icon:
                  type: string
                  format: uri
                  description: URL to the distributor's icon image.
                name:
                  type: string
                  description: The name of the distributor.
    CreateDistributorBlock:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - block_distributor
            attributes:
              type: object
              required:
                - distributor_id
                - reason
              properties:
                distributor_id:
                  type: string
                  format: uuid
                  description: The UUID of the distributor to be blocked.
                reason:
                  type: string
                  description: The reason for blocking the distributor.
    CreateEmployeeInvite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - send_employee_invite
            attributes:
              type: object
              required:
                - distributor_id
                - user_id
                - role
              properties:
                distributor_id:
                  type: string
                  format: uuid
                  description: The UUID of the distributor to which the user is being invited.
                user_id:
                  type: string
                  format: uuid
                  description: The UUID of the user being invited.
                role:
                  type: string
                  description: The role assigned to the invited user within the distributor.
                  enum:
                    - admin
                    - member
    UpdateDistributor:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: The UUID of the distributor to be updated.
            type:
              type: string
              enum:
                - update_distributor
            attributes:
              type: object
              properties:
                icon:
                  type: string
                  format: uri
                  description: URL to the distributor's icon image.
                name:
                  type: string
                  description: The name of the distributor.
    UpdateDistributorStatus:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: The UUID of the distributor to be updated.
            type:
              type: string
              enum:
                - update_distributor_status
            attributes:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum:
                    - active
                    - inactive
                  description: The new status of the distributor.
    PaginationData:
      type: object
      required:
        - page_number
        - page_size
        - total_items
      properties:
        page_number:
          type: integer
          format: int64
          description: The current page number.
          example: 1
        page_size:
          type: integer
          format: int64
          description: The number of items per page.
          example: 10
        total_items:
          type: integer
          format: int64
          description: The total number of items available.
          example: 100
    Errors:
      description: 'Standard JSON:API error'
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          description: Non empty array of errors occurred during request processing
          items:
            type: object
            required:
              - title
              - status
            properties:
              title:
                type: string
                description: 'Title is a short, human-readable summary of the problem'
                example: Bad Request
              detail:
                type: string
                description: Detail is a human-readable explanation specific to this occurrence of the problem
                example: Request body was expected
              status:
                type: integer
                description: Status is the HTTP status code applicable to this problem
                example: 400
                enum:
                  - 400
                  - 401
                  - 403
                  - 404
                  - 409
                  - 500
    Employee:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/EmployeeData'
    EmployeeData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: user id
        type:
          type: string
          enum:
            - employee
        attributes:
          $ref: '#/components/schemas/EmployeeAttributes'
    EmployeeAttributes:
      type: object
      required:
        - distributor_id
        - role
        - created_at
        - updated_at
      properties:
        distributor_id:
          type: string
          format: uuid
          description: The unique identifier for the distributor associated with the employee.
        role:
          type: string
          description: 'The role of the employee within the distributor''s organization (e.g., manager, staff).'
        created_at:
          type: string
          format: date-time
          description: The timestamp when the employee record was created.
        updated_at:
          type: string
          format: date-time
          description: The timestamp when the employee record was last updated.
    EmployeesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/EmployeeData'
        links:
          $ref: '#/components/schemas/PaginationData'
    Invite:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/InviteData'
    InviteData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: invite id
        type:
          type: string
          enum:
            - distributor_invite
        attributes:
          $ref: '#/components/schemas/InviteAttributes'
    InviteAttributes:
      type: object
      required:
        - status
        - role
        - distributor_id
        - token
        - expires_at
        - created_at
      properties:
        status:
          type: string
          description: status of the invite
        role:
          type: string
          description: role of the user in this city
        distributor_id:
          type: string
          format: uuid
          description: distributor id
        token:
          type: string
          description: unique token for the invite
        expires_at:
          type: string
          format: date-time
          description: timestamp when the invite will expire
        created_at:
          type: string
          format: date-time
          description: timestamp when the invite was created
    SentInvite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: invite id
            type:
              type: string
              enum:
                - distributor_invite
            attributes:
              type: object
              required:
                - distributor_id
                - role
              properties:
                distributor_id:
                  type: string
                  format: uuid
                  description: ID of the distributor the invite is for
                role:
                  type: string
                  description: Role assigned to the invited user
    Distributor:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/DistributorData'
    DistributorData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: distributor id
        type:
          type: string
          enum:
            - distributor
        attributes:
          $ref: '#/components/schemas/DistributorAttributes'
    DistributorAttributes:
      type: object
      required:
        - icon
        - name
        - status
        - created_at
        - updated_at
      properties:
        icon:
          type: string
          format: uri
          description: URL to the distributor's icon image.
        name:
          type: string
          description: The name of the distributor.
        status:
          type: string
          description: 'The current status of the distributor (e.g., active, inactive).'
        updated_at:
          type: string
          format: date-time
          description: The timestamp of the last update to the distributor's information.
        created_at:
          type: string
          format: date-time
    DistributorsCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/DistributorData'
        links:
          $ref: '#/components/schemas/PaginationData'
    DistributorBlock:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/DistributorBlockData'
    DistributorBlockData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: distributor block id
        type:
          type: string
          enum:
            - distributor_block
        attributes:
          $ref: '#/components/schemas/DistributorBlockAttributes'
    DistributorBlockAttributes:
      type: object
      required:
        - distributor_id
        - initiator_id
        - reason
        - status
        - blocked_at
      properties:
        distributor_id:
          type: string
          format: uuid
          description: ID of the distributor being blocked
          example: 550e8400-e29b-41d4-a716-446655440000
        initiator_id:
          type: string
          format: uuid
          description: ID of the user who initiated the block
          example: 660e8400-e29b-41d4-a716-446655440000
        reason:
          type: string
          description: Reason for blocking the distributor
          example: Violation of terms of service
        status:
          type: string
          description: Current status of the block
          example: active
        blocked_at:
          type: string
          format: date-time
          description: Timestamp when the block was initiated
          example: '2023-10-01T12:00:00Z'
        cancelled_at:
          type: string
          format: date-time
          description: 'Timestamp when the block was lifted, if applicable'
          example: '2023-10-15T12:00:00Z'
    DistributorBlocksCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/DistributorBlockData'
        links:
          $ref: '#/components/schemas/PaginationData'
