openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    CreateCompany:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - company
            attributes:
              type: object
              required:
                - icon
                - name
              properties:
                icon:
                  type: string
                  format: uri
                  description: URL to the company's icon image.
                name:
                  type: string
                  description: The name of the company.
    CreateCompanyBlock:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - block_company
            attributes:
              type: object
              required:
                - company_id
                - reason
              properties:
                company_id:
                  type: string
                  format: uuid
                  description: The UUID of the company to be blocked.
                reason:
                  type: string
                  description: The reason for blocking the company.
    UpdateCompany:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: The UUID of the company to be updated.
            type:
              type: string
              enum:
                - update_company
            attributes:
              type: object
              properties:
                icon:
                  type: string
                  format: uri
                  description: URL to the company's icon image.
                name:
                  type: string
                  description: The name of the company.
    UpdateCompanyStatus:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: The UUID of the company to be updated.
            type:
              type: string
              enum:
                - company
            attributes:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum:
                    - active
                    - inactive
                  description: The new status of the company.
    UpdateEmployee:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: The UUID of the employee to be updated.
            type:
              type: string
              enum:
                - employee
            attributes:
              type: object
              properties:
                role:
                  type: string
                  description: The role or position of the employee within the company.
                position:
                  type: string
                  description: The job title of the employee.
                label:
                  type: string
                  description: A label or tag associated with the employee.
    UpdateMyEmployee:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - employee
            attributes:
              type: object
              properties:
                position:
                  type: string
                  description: The job title of the employee.
                label:
                  type: string
                  description: A label or tag associated with the employee.
    PaginationData:
      type: object
      required:
        - page_number
        - page_size
        - total_items
      properties:
        page_number:
          type: integer
          format: int64
          description: The current page number.
          example: 1
        page_size:
          type: integer
          format: int64
          description: The number of items per page.
          example: 10
        total_items:
          type: integer
          format: int64
          description: The total number of items available.
          example: 100
    Errors:
      description: 'Standard JSON:API error'
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          description: Non empty array of errors occurred during request processing
          items:
            type: object
            required:
              - title
              - status
            properties:
              title:
                type: string
                description: 'Title is a short, human-readable summary of the problem'
                example: Bad Request
              detail:
                type: string
                description: Detail is a human-readable explanation specific to this occurrence of the problem
                example: Request body was expected
              status:
                type: integer
                description: Status is the HTTP status code applicable to this problem
                example: 400
                enum:
                  - 400
                  - 401
                  - 403
                  - 404
                  - 409
                  - 500
    Employee:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/EmployeeData'
    EmployeeData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: user id
        type:
          type: string
          enum:
            - employee
        attributes:
          $ref: '#/components/schemas/EmployeeAttributes'
    EmployeeAttributes:
      type: object
      required:
        - company_id
        - role
        - created_at
        - updated_at
      properties:
        company_id:
          type: string
          format: uuid
          description: The unique identifier for the company associated with the employee.
        role:
          type: string
          description: 'The role of the employee within the company''s organization (e.g., manager, staff).'
        position:
          type: string
          description: The job position or title of the employee.
        label:
          type: string
          description: A human-readable label or name for the employee.
        created_at:
          type: string
          format: date-time
          description: The timestamp when the employee record was created.
        updated_at:
          type: string
          format: date-time
          description: The timestamp when the employee record was last updated.
    EmployeesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/EmployeeData'
        links:
          $ref: '#/components/schemas/PaginationData'
    Invite:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/InviteData'
    InviteData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: invite id
        type:
          type: string
          enum:
            - company_invite
        attributes:
          $ref: '#/components/schemas/InviteAttributes'
    InviteAttributes:
      type: object
      required:
        - company_id
        - user_id
        - initiator_id
        - status
        - role
        - expires_at
        - created_at
      properties:
        company_id:
          type: string
          format: uuid
          description: company id
        user_id:
          type: string
          format: uuid
          description: user id
        initiator_id:
          type: string
          format: uuid
          description: id of the user who sent the invite
        status:
          type: string
          description: status of the invite
        role:
          type: string
          description: role of the user in this city
        expires_at:
          type: string
          format: date-time
          description: timestamp when the invite will expire
        created_at:
          type: string
          format: date-time
          description: timestamp when the invite was created
    AnswerInvite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: invite id
            type:
              type: string
              enum:
                - company_invite
            attributes:
              type: object
              required:
                - answer
              properties:
                answer:
                  type: string
                  enum:
                    - accept
                    - decline
                  description: 'The answer to the invite, either ''accept'' or ''decline'''
    CreateInvite:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - company_invite
            attributes:
              type: object
              required:
                - company_id
                - user_id
                - role
              properties:
                company_id:
                  type: string
                  format: uuid
                  description: ID of the company the invite is for
                user_id:
                  type: string
                  format: uuid
                  description: ID of the user being invited
                role:
                  type: string
                  description: Role assigned to the invited user
    Company:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/CompanyData'
    CompanyData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: company id
        type:
          type: string
          enum:
            - company
        attributes:
          $ref: '#/components/schemas/CompanyAttributes'
    CompanyAttributes:
      type: object
      required:
        - name
        - icon
        - status
        - created_at
        - updated_at
      properties:
        icon:
          type: string
          format: uri
          description: URL to the company's icon image.
        name:
          type: string
          description: The name of the company.
        status:
          type: string
          description: 'The current status of the company (e.g., active, inactive).'
        updated_at:
          type: string
          format: date-time
          description: The timestamp of the last update to the company's information.
        created_at:
          type: string
          format: date-time
    CompaniesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CompanyData'
        links:
          $ref: '#/components/schemas/PaginationData'
    CompanyBlock:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/CompanyBlockData'
    CompanyBlockData:
      type: object
      required:
        - id
        - type
        - attributes
      properties:
        id:
          type: string
          format: uuid
          description: company block id
        type:
          type: string
          enum:
            - company_block
        attributes:
          $ref: '#/components/schemas/CompanyBlockAttributes'
    CompanyBlockAttributes:
      type: object
      required:
        - company_id
        - initiator_id
        - reason
        - status
        - blocked_at
      properties:
        company_id:
          type: string
          format: uuid
          description: ID of the company being blocked
          example: 550e8400-e29b-41d4-a716-446655440000
        initiator_id:
          type: string
          format: uuid
          description: ID of the user who initiated the block
          example: 660e8400-e29b-41d4-a716-446655440000
        reason:
          type: string
          description: Reason for blocking the company
          example: Violation of terms of services
        status:
          type: string
          description: Current status of the block
          example: active
        blocked_at:
          type: string
          format: date-time
          description: Timestamp when the block was initiated
          example: '2023-10-01T12:00:00Z'
        cancelled_at:
          type: string
          format: date-time
          description: 'Timestamp when the block was lifted, if applicable'
          example: '2023-10-15T12:00:00Z'
    CompanyBlocksCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CompanyBlockData'
        links:
          $ref: '#/components/schemas/PaginationData'
