openapi: 3.0.0
info:
  title: Cifra SSO REST API
  description: SSO REST API for Cifra app
  version: 0.0.1

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
#  /re-news/sso/v1/public/google/login:
#    $ref: './paths/Login.yaml'
#  /re-news/sso/v1/public/refresh:
#    $ref: './paths/Refresh.yaml'
#  /re-news/sso/v1/public/account:
#    $ref: './paths/Account.yaml'
#  /re-news/sso/v1/public/sessions:
#    $ref: './paths/Sessions.yaml'
#  /re-news/sso/v1/public/sessions/{session_id}:
#    $ref: './paths/Session.yaml'
#  /re-news/sso/v1/private/account/{account_id}:
#    $ref: './paths/AccountGetById.yaml'
#  /re-news/sso/v1/private/accounts/{account_id}/{role}:
#    $ref: './paths/AccountRole.yaml'
#  /re-news/sso/v1/private/accounts/{account_id}/sessions:
#    $ref: './paths/AdminGetSessions.yaml'
#  /re-news/sso/v1/private/accounts/{account_id}/sessions/{session_id}:
#    $ref: './paths/AdminGetSession.yaml'

components:
  schemas:
    #requests
    CreateCompany:
      $ref: './spec/components/schemas/CreateCompany.yaml'
    CreateCompanyBlock:
      $ref: './spec/components/schemas/CreateCompanyBlock.yaml'
    CreateEmployeeInvite:
      $ref: './spec/components/schemas/CreateEmployeeInvite.yaml'
    UpdateCompany:
      $ref: './spec/components/schemas/UpdateCompany.yaml'
    UpdateCompanyStatus:
      $ref: './spec/components/schemas/UpdateCompanyStatus.yaml'


    #responses
    PaginationData:
      $ref: './spec/components/schemas/PaginationData.yaml'
    Errors:
      $ref: './spec/components/schemas/Errors.yaml'
    Employee:
      $ref: './spec/components/schemas/Employee.yaml'
    EmployeeData:
      $ref: './spec/components/schemas/EmployeeData.yaml'
    EmployeeAttributes:
      $ref: './spec/components/schemas/EmployeeAttributes.yaml'
    EmployeesCollection:
      $ref: './spec/components/schemas/EmployeesCollection.yaml'
    Invite:
      $ref: './spec/components/schemas/Invite.yaml'
    InviteData:
      $ref: './spec/components/schemas/InviteData.yaml'
    InviteAttributes:
      $ref: './spec/components/schemas/InviteAttributes.yaml'
    SentInvite:
      $ref: './spec/components/schemas/SentInvite.yaml'
    Company:
        $ref: './spec/components/schemas/Company.yaml'
    CompanyData:
        $ref: './spec/components/schemas/CompanyData.yaml'
    CompanyAttributes:
        $ref: './spec/components/schemas/CompanyAttributes.yaml'
    CompaniesCollection:
        $ref: './spec/components/schemas/CompaniesCollection.yaml'
    CompanyBlock:
        $ref: './spec/components/schemas/CompanyBlock.yaml'
    CompanyBlockData:
        $ref: './spec/components/schemas/CompanyBlockData.yaml'
    CompanyBlockAttributes:
        $ref: './spec/components/schemas/CompanyBlockAttributes.yaml'
    CompanyBlocksCollection:
       $ref: './spec/components/schemas/CompanyBlocksCollection.yaml'
